### ISSUE TITLE
IOperation, IOperationData and ICalculator should be in separate project

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.MEF.Example#1]
In a real world scenario the definitions for
* [`IOperation`](../blob/e3c52a7219aedde365ab5265650c1030b5a1f293/SimpleCalculator3/IOperation.cs#10)
* [`IOperationData`](../blob/e3c52a7219aedde365ab5265650c1030b5a1f293/SimpleCalculator3/IOperationData.cs#13)
* [`ICalculator`](../blob/e3c52a7219aedde365ab5265650c1030b5a1f293/SimpleCalculator3/ICalculator.cs#5)

should be kept in a separate project, so the importer and the exporter (the actual extension) can reference it.

For this example it will not be fixed.

**Comment by rufer7** [comment]
fixed and as well bumped the .NET FW version to 4.5 (was 4)
